// czn-speed -- Zygisk runtime speed-control module for
// com.smilegate.chaoszero.stove.google (CHAOS ZERO NIGHTMARE).
// Injects a JS layer into the game's own V8 context; the official APK is
// never modified and the module is passive after installation.

#include <jni.h>
#include <pthread.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <elf.h>
#include <link.h>
#include <time.h>
#include <fcntl.h>
#include <dirent.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdarg.h>
#include <android/log.h>

#define LOG_TAG "CZN"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

static const char TARGET_PKG[] = "com.smilegate.chaoszero.stove.google";
static const char ENGINE_LIB[] = "libssr.so";
#define SLOT_CAP 32

// ---------------------------------------------------------------- V8 symbols
typedef void *(*fn_Isolate_GetCurrent)();
typedef void *(*fn_Isolate_GetCurrentContext)(void *isolate);
typedef void *(*fn_String_NewFromUtf8)(void *isolate, const char *buf, int type, int len);
typedef void *(*fn_Script_Compile)(void *ctx, void *src, void *origin);
typedef void *(*fn_Script_Run)(void *script, void *ctx);
typedef void (*fn_TryCatch_Ctor)(void *self, void *isolate);
typedef void (*fn_TryCatch_Dtor)(void *self);
typedef void (*fn_HandleScope_Ctor)(void *self, void *isolate);
typedef void (*fn_HandleScope_Dtor)(void *self);
typedef void *(*fn_TryCatch_Message)(void *self);
typedef void *(*fn_Message_Get)(void *self);
typedef int (*fn_String_WriteOneByte)(void *self, void *isolate, unsigned char *buf, int start, int len, int opts);
typedef void (*fn_TerminateExecution)(void *isolate);

static fn_Isolate_GetCurrent        v8_Isolate_GetCurrent;
static fn_Isolate_GetCurrentContext v8_Isolate_GetCurrentContext;
static fn_String_NewFromUtf8        v8_String_NewFromUtf8;
static fn_Script_Compile            v8_Script_Compile;
static fn_Script_Run                v8_Script_Run;
static fn_TryCatch_Ctor             v8_TryCatch_Ctor;
static fn_TryCatch_Dtor             v8_TryCatch_Dtor;
static fn_HandleScope_Ctor          v8_HandleScope_Ctor;
static fn_HandleScope_Dtor          v8_HandleScope_Dtor;
static fn_TryCatch_Message          v8_TryCatch_Message;
static fn_Message_Get               v8_Message_Get;
static fn_String_WriteOneByte       v8_String_WriteOneByte;
static fn_TerminateExecution        v8_TerminateExecution;
static fn_TerminateExecution        v8_CancelTerminateExecution;

struct V8Sym { const char *name; void *addr; };
static struct V8Sym kV8Syms[] = {
    { "_ZN2v87Isolate10GetCurrentEv", NULL },
    { "_ZN2v87Isolate17GetCurrentContextEv", NULL },
    { "_ZN2v86String11NewFromUtf8EPNS_7IsolateEPKcNS_13NewStringTypeEi", NULL },
    { "_ZN2v86Script7CompileENS_5LocalINS_7ContextEEENS1_INS_6StringEEEPNS_12ScriptOriginE", NULL },
    { "_ZN2v86Script3RunENS_5LocalINS_7ContextEEE", NULL },
    { "_ZN2v88TryCatchC1EPNS_7IsolateE", NULL },
    { "_ZN2v88TryCatchD1Ev", NULL },
    { "_ZN2v811HandleScopeC1EPNS_7IsolateE", NULL },
    { "_ZN2v811HandleScopeD1Ev", NULL },
    { "_ZNK2v88TryCatch7MessageEv", NULL },
    { "_ZNK2v87Message3GetEv", NULL },
    { "_ZNK2v86String12WriteOneByteEPNS_7IsolateEPhiii", NULL },
    { "_ZN2v87Isolate18TerminateExecutionEv", NULL },
    { "_ZN2v87Isolate24CancelTerminateExecutionEv", NULL },
};

// ---------------------------------------------------------------- state
#define ST_IDLE    0
#define ST_ARMED   1
#define ST_DONE    2
#define ST_FAILED  (-1)
static volatile int g_state = ST_IDLE;
static volatile int g_injecting = 0;
static volatile long g_last_try_ms = 0;
static volatile long g_inject_start_ms = 0;
static volatile void *g_cur_iso = NULL;
static volatile int g_watchdog_fired = 0;
static int g_mem_fd = -1;
static int g_is_main_proc = -1;    // -1 unknown, 0 fork-child, 1 main

static uintptr_t g_engine_base = 0;
static uintptr_t g_v8_cage = 0;    // advisory: only set on ptr-compression builds

struct Slot { void **slot; void *orig; };
static struct Slot g_slots[SLOT_CAP];
static int g_slot_count = 0;

// embedded JS layer (generated by gen_headers.py from the assembled bundle)
#include "mod_js.h"

// ---------------------------------------------------------------- utils
static long now_ms() {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long)ts.tv_sec * 1000L + ts.tv_nsec / 1000000L;
}

// raw open/read — never fopen (those are our own hook points)
static int read_file_head(const char *path, char *out, int cap) {
    int fd = open(path, O_RDONLY);
    if (fd < 0) return -1;
    ssize_t n = read(fd, out, cap - 1);
    close(fd);
    if (n <= 0) return -1;
    out[n] = 0;
    return (int)n;
}

// main process = many threads; the engine's fork-child watchdog has exactly 1
static int is_main_process() {
    if (g_is_main_proc >= 0) return g_is_main_proc;
    g_is_main_proc = 0;
    char buf[2048];
    if (read_file_head("/proc/self/status", buf, sizeof(buf) - 1) < 0) return 0;
    const char *p = strstr(buf, "Threads:");
    if (p) {
        int t = atoi(p + 8);
        g_is_main_proc = (t > 1) ? 1 : 0;
    }
    return g_is_main_proc;
}

// ---------------------------------------------------------------- maps scan
static int find_engine_base(uintptr_t *out, char *path_out, int path_cap) {
    static const size_t CAP = 2u << 20;
    char *buf = (char *)malloc(CAP);
    if (!buf) return -1;
    int fd = open("/proc/self/maps", O_RDONLY);
    if (fd < 0) { free(buf); return -1; }
    size_t total = 0;
    for (;;) {
        if (total >= CAP - 1) break;
        ssize_t n = read(fd, buf + total, CAP - 1 - total);
        if (n <= 0) break;
        total += (size_t)n;
    }
    close(fd);
    buf[total] = 0;
    uintptr_t best = 0;
    char best_path[256] = {0};
    char *save = NULL;
    for (char *line = strtok_r(buf, "\n", &save); line; line = strtok_r(NULL, "\n", &save)) {
        if (!strstr(line, ENGINE_LIB)) continue;
        uintptr_t lo = strtoull(line, NULL, 16);
        if (best == 0 || lo < best) {
            best = lo;
            char *p = strrchr(line, ' ');
            if (p && p[1] == '/') {
                snprintf(best_path, sizeof(best_path), "%s", p + 1);
                size_t L = strlen(best_path);
                while (L && (best_path[L-1] == '\n' || best_path[L-1] == '\r')) best_path[--L] = 0;
            }
        }
    }
    free(buf);
    if (!best) return -1;
    *out = best;
    if (path_out && path_cap > 0) snprintf(path_out, path_cap, "%s", best_path);
    return 0;
}

// ---------------------------------------------------------------- V8 ready
// The embedded V8's platform worker threads (named "V8 DefaultWorke…" etc.)
// exist only after V8 has been initialized — a version-independent readiness
// signal that works with or without pointer compression. Pure procfs scan.
static int v8_platform_ready(void) {
    DIR *d = opendir("/proc/self/task");
    if (!d) return 0;
    struct dirent *e;
    int found = 0;
    while (!found && (e = readdir(d)) != NULL) {
        if (e->d_name[0] < '0' || e->d_name[0] > '9') continue;
        char path[64], comm[64];
        snprintf(path, sizeof(path), "/proc/self/task/%s/comm", e->d_name);
        int fd = open(path, O_RDONLY);
        if (fd < 0) continue;
        ssize_t n = read(fd, comm, sizeof(comm) - 1);
        close(fd);
        if (n < 4) continue;
        comm[(n < (ssize_t)sizeof(comm) - 1) ? n : (ssize_t)sizeof(comm) - 1] = 0;
        if (comm[0] == 'V' && comm[1] == '8' && (comm[2] == ' ' || comm[2] == 0))
            found = 1;
    }
    closedir(d);
    return found;
}

// ---------------------------------------------------------------- mem probe
// Without a pointer-compression cage there is no structural equality check
// for Isolate::GetCurrent() results, so verify the address is actually
// readable via /proc/self/mem (exact: EFAULT on unmapped, one pread).
static int addr_readable(uintptr_t addr) {
    if (g_mem_fd < 0) {
        g_mem_fd = open("/proc/self/mem", O_RDONLY);
        if (g_mem_fd < 0) return 1;  // cannot probe: fail open (validated by the probe script)
    }
    char c;
    return pread(g_mem_fd, &c, 1, (off_t)addr) == 1;
}

// ---------------------------------------------------------------- V8 cage
// Advisory only: on pointer-compression builds the real Isolate sits at the
// 4GB-aligned cage base and equality with GetCurrent() is the strongest
// validity check. This engine's V8 is built without it (the probe returns
// -1 and the mem-probe path is used instead).
static int find_v8_cage(uintptr_t *out) {
    static const size_t CAP = 2u << 20;
    char *buf = (char *)malloc(CAP);
    if (!buf) return -1;
    int fd = open("/proc/self/maps", O_RDONLY);
    if (fd < 0) { free(buf); return -1; }
    size_t total = 0;
    for (;;) {
        if (total >= CAP - 1) break;
        ssize_t n = read(fd, buf + total, CAP - 1 - total);
        if (n <= 0) break;
        total += (size_t)n;
    }
    close(fd);
    buf[total] = 0;
    uintptr_t found = 0;
    char *save = NULL;
    for (char *line = strtok_r(buf, "\n", &save); line; line = strtok_r(NULL, "\n", &save)) {
        char *dash = strchr(line, '-');
        if (!dash) continue;
        *dash = 0;
        uintptr_t lo = strtoull(line, NULL, 16);
        uintptr_t hi = strtoull(dash + 1, NULL, 16);
        if (hi > lo && (hi - lo) == 0x100000000ULL && (lo & 0xFFFFFFFFULL) == 0) {
            found = lo;
            break;
        }
    }
    free(buf);
    if (!found) return -1;
    *out = found;
    return 0;
}

// ---------------------------------------------------------------- ELF parse
struct DynInfo {
    ElfW(Sym) *symtab;
    const char *strtab;
    uint32_t symcount;      // via GNU_HASH walk
    uintptr_t gnu_hash;
    ElfW(Rela) *jmprel;
    size_t pltrelsz;
    ElfW(Rela) *rela;
    size_t relasz;
    uintptr_t span;         // max(vaddr + memsz) — sanity bound
};

// symbol count from DT_GNU_HASH: max bucket index, then walk chain to terminator
static uint32_t gnu_hash_symcount(uintptr_t gnu_hash_addr) {
    const uint32_t *h = (const uint32_t *)gnu_hash_addr;
    uint32_t nbuckets = h[0], symoffset = h[1], bloom_size = h[2];
    if (!nbuckets || !bloom_size || bloom_size > (1u << 20)) return 0;
    const uint64_t *bloom = (const uint64_t *)(h + 4);
    const uint32_t *buckets = (const uint32_t *)((const char *)bloom + (size_t)bloom_size * 8);
    const uint32_t *chain = buckets + nbuckets;
    uint32_t max_idx = 0;
    for (uint32_t i = 0; i < nbuckets; i++)
        if (buckets[i] > max_idx) max_idx = buckets[i];
    if (max_idx < symoffset) return symoffset;
    for (uint32_t guard = 0; guard < (4u << 20); guard++) {
        uint32_t v = chain[max_idx - symoffset];
        if (v & 1) return max_idx + 1;
        max_idx++;
    }
    return 0;
}

static int parse_dynamic(uintptr_t base, struct DynInfo *di) {
    memset(di, 0, sizeof(*di));
    ElfW(Ehdr) *ehdr = (ElfW(Ehdr) *)base;
    if (memcmp(ehdr->e_ident, ELFMAG, SELFMAG) != 0) return -1;
    ElfW(Phdr) *phdr = (ElfW(Phdr) *)(base + ehdr->e_phoff);
    ElfW(Dyn) *dyn = NULL;
    for (int i = 0; i < ehdr->e_phnum; i++) {
        if (phdr[i].p_type == PT_LOAD) {
            uintptr_t end = base + phdr[i].p_vaddr + phdr[i].p_memsz;
            if (end > di->span) di->span = end;
        }
        if (phdr[i].p_type == PT_DYNAMIC) dyn = (ElfW(Dyn) *)(base + phdr[i].p_vaddr);
    }
    if (!dyn || !di->span) return -1;
    ElfW(Sym) *symtab = NULL;
    const char *strtab = NULL;
    for (ElfW(Dyn) *d = dyn; d->d_tag != DT_NULL; d++) {
        switch (d->d_tag) {
            case DT_SYMTAB:  symtab = (ElfW(Sym) *)(base + d->d_un.d_ptr); break;
            case DT_STRTAB:  strtab = (const char *)(base + d->d_un.d_ptr); break;
            case DT_GNU_HASH: di->gnu_hash = base + d->d_un.d_ptr; break;
            case DT_JMPREL:  di->jmprel = (ElfW(Rela) *)(base + d->d_un.d_ptr); break;
            case DT_PLTRELSZ: di->pltrelsz = d->d_un.d_val; break;
            case DT_RELA:    di->rela = (ElfW(Rela) *)(base + d->d_un.d_ptr); break;
            case DT_RELASZ:  di->relasz = d->d_un.d_val; break;
        }
    }
    if (!symtab || !strtab) return -1;
    di->symtab = symtab;
    di->strtab = strtab;
    if (di->gnu_hash) di->symcount = gnu_hash_symcount(di->gnu_hash);
    // bound symcount by the strtab distance (symtab precedes strtab in lld layout)
    if (strtab && (uintptr_t)strtab > (uintptr_t)symtab) {
        uint32_t cap = (uint32_t)(((uintptr_t)strtab - (uintptr_t)symtab) / sizeof(ElfW(Sym)));
        if (di->symcount == 0 || di->symcount > cap) di->symcount = cap;
    }
    if (di->symcount == 0 || di->symcount > (1u << 21)) return -1;
    if ((uintptr_t)di->symtab < base || (uintptr_t)di->symtab > di->span) return -1;
    if ((uintptr_t)di->strtab < base || (uintptr_t)di->strtab > di->span) return -1;
    return 0;
}

static void *find_symbol(struct DynInfo *di, const char *name) {
    for (uint32_t i = 0; i < di->symcount; i++) {
        const ElfW(Sym) *s = &di->symtab[i];
        if (!s->st_value || !s->st_name) continue;
        const char *nm = di->strtab + s->st_name;
        if (nm[0] == name[0] && strcmp(nm, name) == 0)
            return (void *)(g_engine_base + s->st_value);
    }
    return NULL;
}

// ---------------------------------------------------------------- GOT patch
static int unprotect(void *addr, size_t len) {
    uintptr_t p = (uintptr_t)addr & ~0xfffUL;
    size_t span = ((uintptr_t)addr + len - p + 0xfff) & ~0xfffUL;
    return mprotect((void *)p, span, PROT_READ | PROT_WRITE);
}

static int reprotect(void *addr, size_t len) {
    uintptr_t p = (uintptr_t)addr & ~0xfffUL;
    size_t span = ((uintptr_t)addr + len - p + 0xfff) & ~0xfffUL;
    return mprotect((void *)p, span, PROT_READ);
}

static void restore_all_slots() {
    for (int i = 0; i < g_slot_count; i++) {
        unprotect(g_slots[i].slot, sizeof(void *));
        *g_slots[i].slot = g_slots[i].orig;
        reprotect(g_slots[i].slot, sizeof(void *));
    }
    g_slot_count = 0;
}

// Patch every JUMP_SLOT/GLOB_DAT relocation whose symbol name matches `sym`.
// The original address is captured BEFORE overwriting and handed back via
// orig_out so the hook can pass through genuinely.
static int patch_symbol(struct DynInfo *di, const char *sym, void *hook, void **orig_out) {
    int patched = 0;
    for (int pass = 0; pass < 2; pass++) {
        ElfW(Rela) *tab = pass == 0 ? di->jmprel : di->rela;
        size_t sz = pass == 0 ? di->pltrelsz : di->relasz;
        if (!tab || !sz) continue;
        size_t n = sz / sizeof(ElfW(Rela));
        for (size_t i = 0; i < n; i++) {
            uint32_t type = ELF64_R_TYPE(tab[i].r_info);
            if (type != R_AARCH64_JUMP_SLOT && type != R_AARCH64_GLOB_DAT) continue;
            size_t sidx = ELF64_R_SYM(tab[i].r_info);
            const char *nm = di->strtab + di->symtab[sidx].st_name;
            if (strcmp(nm, sym) != 0) continue;
            if (g_slot_count >= SLOT_CAP) return patched > 0 ? patched : -1;
            void **slot = (void **)(g_engine_base + tab[i].r_offset);
            void *real = *slot;              // resolve BEFORE overwriting
            if (orig_out && real) *orig_out = real;
            if (unprotect(slot, sizeof(void *)) != 0) return -1;
            g_slots[g_slot_count].slot = slot;
            g_slots[g_slot_count].orig = real;
            g_slot_count++;
            *slot = hook;
            reprotect(slot, sizeof(void *));
            patched++;
        }
    }
    return patched > 0 ? patched : -1;
}

// ---------------------------------------------------------------- injection
static int eval_source(void *iso, void *ctx, const char *src, size_t len,
                       char *errmsg, int errcap, char *out1) {
    // scope objects: generous fixed buffers (HandleScope=24B, TryCatch<=72B)
    alignas(16) char hs[64];
    alignas(16) char tc[256];
    v8_HandleScope_Ctor(hs, iso);
    v8_TryCatch_Ctor(tc, iso);
    void *result = NULL;
    void *str = v8_String_NewFromUtf8(iso, src, 0 /*kNormal*/, (int)len);
    if (str) {
        void *script = v8_Script_Compile(ctx, str, NULL);
        if (script) result = v8_Script_Run(script, ctx);
    }
    // on failure, pull the JS exception text out natively (the engine's
    // console is silenced — this is the only reliable channel)
    if (errmsg && errcap > 0) {
        errmsg[0] = 0;
        if (!result) {
            void *mobj = v8_TryCatch_Message(tc);
            if (mobj) {
                void *mstr = v8_Message_Get(mobj);
                if (mstr)
                    v8_String_WriteOneByte(mstr, iso, (unsigned char *)errmsg, 0, errcap - 1, 0);
                errmsg[errcap - 1] = 0;
            }
        }
    }
    // the installed script returns a 1-char JS string ("0"/"1"); hand the
    // first byte back to the caller for state dispatch
    if (out1 && result)
        v8_String_WriteOneByte(result, iso, (unsigned char *)out1, 0, 1, 0);
    v8_TryCatch_Dtor(tc);
    v8_HandleScope_Dtor(hs);
    return result != NULL;
}

// ---------------------------------------------------------------- status
// Tiny persistent status (overwritten in place, ~200B) so state survives
// logcat rotation and is checkable over adb. No version prefix, no timestamp.
static void status_write(const char *msg) {
    char path[160];
    snprintf(path, sizeof(path),
             "/storage/emulated/0/Android/data/%s/files/.czn_status", TARGET_PKG);
    int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0644);
    if (fd < 0) return;
    ssize_t w = write(fd, msg, strlen(msg));
    (void)w;
    close(fd);
}

// ---------------------------------------------------------------- hooks
static void *(*orig_AAsset_read)(void *, void *, size_t);
static void *(*orig_AAssetManager_open)(void *, const char *, int);
static void maybe_inject();

static void *hook_AAsset_read(void *a, void *buf, size_t len) {
    maybe_inject();
    return orig_AAsset_read(a, buf, len);
}
static void *hook_AAssetManager_open(void *mgr, const char *path, int mode) {
    maybe_inject();
    return orig_AAssetManager_open(mgr, path, mode);
}

struct HookDef { const char *sym; void *hook; void **orig_ptr; };
// minimal trigger surface — asset reads only (these fire on the JS thread
// during scene loads). Capture the real addresses so the hooks pass through
// genuinely; an unassigned orig pointer would let the compiler delete the
// hook tail entirely (undefined-behaviour folding).
static const struct HookDef kHooks[] = {
    { "AAsset_read",         (void *)hook_AAsset_read,         (void **)&orig_AAsset_read },
    { "AAssetManager_open",  (void *)hook_AAssetManager_open,  (void **)&orig_AAssetManager_open },
};

// ---------------------------------------------------------------- injection
static void maybe_inject() {
    if (g_state != ST_ARMED) return;
    long now = now_ms();
    long last = g_last_try_ms;
    if (now - last < 500) return;                // throttle attempts
    g_last_try_ms = now;
    if (g_is_main_proc < 0 && !is_main_process()) return;  // fork-child: never
    if (g_is_main_proc == 0) return;

    if (__sync_lock_test_and_set(&g_injecting, 1)) return; // reentry guard
    g_inject_start_ms = now;
    do {
        void *iso = v8_Isolate_GetCurrent();
        if (!iso) break;
        // Isolate validation: with pointer compression the real Isolate sits
        // at the 4GB-aligned cage base — exact equality. Without it (this
        // engine), verify the address is readable (/proc/self/mem, exact).
        if (g_v8_cage) {
            if ((uintptr_t)iso != g_v8_cage) break;
        } else if (!addr_readable((uintptr_t)iso)) {
            break;
        }
        g_cur_iso = iso;
        void *ctx = v8_Isolate_GetCurrentContext(iso);
        if (!ctx) break;
        // ONE throw-proof install script (pure definitions + scheduler frame
        // wrap; zero engine mutation at eval time). Its string result
        // carries state: "1"=installed, "0"=engine not ready (retry later).
        char emsg[384] = {0};
        char r[2] = {0, 0};
        if (!eval_source(iso, ctx, kModJs, sizeof(kModJs) - 1, emsg, sizeof(emsg), r)) {
            g_state = ST_FAILED;
            if (g_watchdog_fired) {
                LOGE("stage1 terminated by watchdog");
                status_write("FAIL: watchdog terminated eval (game survived)");
                if (v8_CancelTerminateExecution) v8_CancelTerminateExecution(iso);
            } else {
                LOGE("stage1 failed: %s", emsg[0] ? emsg : "(no message)");
                status_write("FAIL: stage1 script error");
            }
            restore_all_slots();
            break;
        }
        if (r[0] == '1') {
            g_state = ST_DONE;
            LOGI("stage1 ok (frame-driven boot armed)");
            status_write("stage1 ok; boot runs on engine frame");
            restore_all_slots();                 // handlers never run again
        }
        // r[0] == '0': engine not ready yet — stay armed, retry throttled
    } while (0);
    g_cur_iso = NULL;
    g_injecting = 0;
}

// ---------------------------------------------------------------- worker
static void *worker_main(void *) {
    char lib_path[256] = {0};
    // 1) wait for libssr.so -- this IS the game filter (only the game has
    //    this library). 15s early exit for non-game processes.
    int found = 0;
    for (int i = 0; i < 15; i++) {
        if (g_state != ST_IDLE) return NULL;
        if (find_engine_base(&g_engine_base, lib_path, sizeof(lib_path)) == 0) { found = 1; break; }
        sleep(1);
    }
    if (!found) return NULL;

    LOGI("target matched (libssr.so @ %lx)", (unsigned long)g_engine_base);
    status_write("target matched");
    // 1b) wait for V8 initialization via platform worker threads; arm before
    //     that and Isolate::GetCurrent() hands us garbage (uninitialized TLS)
    int v8_ready = 0;
    for (int i = 0; i < 30 * 60; i++) {
        if (g_state != ST_IDLE) return NULL;
        if (v8_platform_ready()) { v8_ready = 1; break; }
        sleep(1);
    }
    if (!v8_ready) { LOGE("v8 platform never appeared; inert exit"); status_write("FAIL: no v8 threads"); return NULL; }
    // advisory cage probe (strong validator on ptr-compression builds only)
    if (find_v8_cage(&g_v8_cage) == 0) {
        LOGI("v8 cage @ %lx", (unsigned long)g_v8_cage);
    }
    // 2) settle: brief pause so the boot's hottest linker phase drains
    for (int i = 0; i < 5; i++) {
        if (g_state != ST_IDLE) return NULL;
        sleep(1);
    }
    // 3) resolve the V8 API from the mapped ELF — no dlopen/dlsym
    struct DynInfo di;
    if (parse_dynamic(g_engine_base, &di) != 0) {
        LOGE("elf parse failed; inert exit");
        status_write("FAIL: elf parse failed");
        return NULL;
    }
    for (unsigned i = 0; i < sizeof(kV8Syms) / sizeof(kV8Syms[0]); i++) {
        kV8Syms[i].addr = find_symbol(&di, kV8Syms[i].name);
        if (!kV8Syms[i].addr) {
            LOGE("symbol missing: %s (engine update? staying inert)", kV8Syms[i].name);
            status_write("FAIL: symbol missing");
            return NULL;
        }
    }
    v8_Isolate_GetCurrent        = (fn_Isolate_GetCurrent)kV8Syms[0].addr;
    v8_Isolate_GetCurrentContext = (fn_Isolate_GetCurrentContext)kV8Syms[1].addr;
    v8_String_NewFromUtf8        = (fn_String_NewFromUtf8)kV8Syms[2].addr;
    v8_Script_Compile            = (fn_Script_Compile)kV8Syms[3].addr;
    v8_Script_Run                = (fn_Script_Run)kV8Syms[4].addr;
    v8_TryCatch_Ctor             = (fn_TryCatch_Ctor)kV8Syms[5].addr;
    v8_TryCatch_Dtor             = (fn_TryCatch_Dtor)kV8Syms[6].addr;
    v8_HandleScope_Ctor          = (fn_HandleScope_Ctor)kV8Syms[7].addr;
    v8_HandleScope_Dtor          = (fn_HandleScope_Dtor)kV8Syms[8].addr;
    v8_TryCatch_Message          = (fn_TryCatch_Message)kV8Syms[9].addr;
    v8_Message_Get               = (fn_Message_Get)kV8Syms[10].addr;
    v8_String_WriteOneByte       = (fn_String_WriteOneByte)kV8Syms[11].addr;
    v8_TerminateExecution        = (fn_TerminateExecution)kV8Syms[12].addr;
    v8_CancelTerminateExecution  = (fn_TerminateExecution)kV8Syms[13].addr;
    // 4) arm transient GOT hooks
    int armed = 0;
    for (unsigned i = 0; i < sizeof(kHooks) / sizeof(kHooks[0]); i++) {
        int n = patch_symbol(&di, kHooks[i].sym, kHooks[i].hook, kHooks[i].orig_ptr);
        if (n < 0) LOGE("patch miss: %s", kHooks[i].sym);
        else { armed += n; LOGI("armed %s (%d slot%s)", kHooks[i].sym, n, n == 1 ? "" : "s"); }
    }
    if (armed == 0) { LOGE("no slots armed; inert exit"); status_write("FAIL: no slots armed"); return NULL; }
    g_state = ST_ARMED;
    status_write("armed; waiting for js thread");
    // 5) park until done; hard cap 2h then disarm (handlers turn transparent)
    long armed_at = now_ms();
    while (g_state == ST_ARMED) {
        sleep(2);
        long t = now_ms();
        if (t - armed_at > 2L * 3600 * 1000) {
            LOGI("timeout: disarming");
            restore_all_slots();
            g_state = ST_FAILED;
            status_write("FAIL: armed timeout (2h)");
            break;
        }
        // watchdog: a stuck eval must never wedge the game. Ask V8 to
        // terminate the running script; our TryCatch absorbs the termination,
        // maybe_inject restores the slots and cancels the terminal state.
        if (!g_watchdog_fired && g_injecting && g_cur_iso &&
            t - g_inject_start_ms > 5000 && v8_TerminateExecution) {
            g_watchdog_fired = 1;
            LOGE("watchdog: eval stuck >5s, terminating execution");
            status_write("watchdog: terminating stuck eval");
            v8_TerminateExecution((void *)g_cur_iso);
            for (int i = 0; i < 50 && g_injecting; i++) usleep(100 * 1000);
            if (v8_CancelTerminateExecution && g_cur_iso)
                v8_CancelTerminateExecution((void *)g_cur_iso);
        }
    }
    return NULL;
}

// ---------------------------------------------------------------- zygisk abi
// Minimal ABI surface: only `registerModule` (table[1], position invariant in
// zygisk api v2..v5) + module_abi layout. No other Api calls are used.
struct ModuleAbi {
    long api_version;
    void *impl;
    void (*preApp)(void *, void *);
    void (*postApp)(void *, const void *);
    void (*preServer)(void *, void *);
    void (*postServer)(void *, const void *);
};

static void pre_app(void *, void *) {}
static void pre_server(void *, void *) {}
static void post_server(void *, const void *) {}

static void post_app(void *, const void *) {
    // Start worker unconditionally -- the worker identifies the game process
    // by detecting libssr.so in /proc/self/maps, which is reliable on all
    // Android versions. /proc/self/cmdline is NOT used because setArgV0
    // timing relative to postAppSpecialize varies across Android versions
    // (verified: Android 15 matches, Android 17 does not).
    pthread_t tid;
    if (pthread_create(&tid, NULL, worker_main, NULL) == 0)
        pthread_detach(tid);
}

extern "C" __attribute__((visibility("default")))
void zygisk_module_entry(void **table, JNIEnv *env) {
    (void)env;
    static ModuleAbi abi;
    abi.api_version = 4;   // v4 ABI: identical module_abi, accepted by all loaders
    abi.impl = (void *)&g_state;
    abi.preApp = pre_app;
    abi.postApp = post_app;
    abi.preServer = pre_server;
    abi.postServer = post_server;
    auto registerModule = reinterpret_cast<bool (*)(void **, ModuleAbi *)>(table[1]);
    registerModule(table, &abi);
}
